---
name: 🔒 Security vulnerability
labels: ["security"]
assignees: francisjgarcia
description: |
  Use this template to report any security vulnerabilities or potential risks.
body:
  - type: textarea
    attributes:
      label: 🔒 Vulnerability description
      description: Provide a detailed description of the security vulnerability.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💥 Potential impact
      description: What could happen if this vulnerability is exploited?
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🛠 Steps to reproduce
      description: Please provide steps or code to reproduce the vulnerability if possible.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🔐 Suggested mitigation
      description: Provide any suggestions on how to fix or mitigate this vulnerability.
    validations:
      required: false
  - type: textarea
    attributes:
      label: ℹ️ Additional information
      description: Add any other relevant details that can help assess the vulnerability.
    validations:
      required: false
