services:
  straperr:
    container_name: straperr
    hostname: straperr
    image: ghcr.io/francisjgarcia/straperr:local
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.local
    networks:
      plex_services_network:
    dns:
      - ${DNS1:-8.8.8.8}
      - ${DNS2:-8.8.4.4}
    volumes:
      - ../src:/app
      - ../tests:/app/tests
    env_file:
      - .env
      - ../src/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status"]
      start_period: 30s
      interval: 1h
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 6M
    restart: always

networks:
  plex_services_network:
    external: true
