services:
  template:
    container_name: template
    image: ghcr.io/francisjgarcia/template:local
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.local
    ports:
      - '${APP_PORT:-5000}:5000'
    env_file:
      - .env
    volumes:
      - ../src:/app
      - ../tests:/app/tests
    user: root
    tty: true
    command: /bin/sh
    restart: on-failure
