---
extends: default

rules:
  line-length:
    max: 180
    level: warning
  indentation:
    spaces: 2
  trailing-spaces:
    level: error
  document-start:
    level: error
  truthy:
    level: warning
    allowed-values: ['true', 'false', 'on', 'off']
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
    level: error
  new-line-at-end-of-file:
    level: error
  comments-indentation:
    level: warning
