---
name: Deploy application to server

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  actions: write

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  setup:
    name: Setup environment
    uses: francisjgarcia/actions-templates/.github/workflows/wf-setup.yml@main

  prepare-secrets:
    name: Prepare deploy secrets
    needs: [setup]
    runs-on: ubuntu-latest
    environment: production
    outputs:
      secret_env_vars: ${{ steps.build.outputs.secret_env_vars }}
    steps:
      - name: Build SECRET_ENV_VARS
        id: build
        env:
          HDOLIMPO_USERNAME: ${{ secrets.HDOLIMPO_USERNAME }}
        run: |
          JSON=$(jq -cn \
            --arg hdolimpo_username "$HDOLIMPO_USERNAME"
            '{
              "straperr": {
                "HDOLIMPO_USERNAME": $hdolimpo_username
              }
            }')
          echo "secret_env_vars=$JSON" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to server
    needs: [setup, prepare-secrets]
    if: needs.setup.outputs.tag_version != ''
    uses: francisjgarcia/actions-templates/.github/workflows/wf-deploy.yml@main
    with:
      tag_version:       ${{ needs.setup.outputs.tag_version }}
      github_repository: ${{ github.repository }}
      secret_env_vars:   ${{ needs.prepare-secrets.outputs.secret_env_vars }}
      containers: |
        [
          {
            "name": "straperr",
            "image": "ghcr.io/${{ github.repository }}:${{ needs.setup.outputs.tag_version }}",
            "network": "${{ vars.DOCKER_NETWORK }}",
            "healthcheck_url": "${{ vars.DOCKER_HEALTHCHECK_URL }}",
            "memory_limit": "${{ vars.DOCKER_MEMORY_LIMIT }}",
            "memory_reservation": "${{ vars.DOCKER_MEMORY_RESERVATION }}",
            "extra_networks": ["${{ vars.DOCKER_NETWORK_STRAPERR }}"],
            "env_vars": {
              "PUID": "1000",
              "PGID": "1000",
              "TZ": "Europe/Madrid",
              "FLASK_ENV": "${{ vars.FLASK_ENV }}",
              "FLASK_DEBUG": "${{ vars.FLASK_DEBUG }}",
              "SONARR_API_URL": "${{ vars.SONARR_API_URL }}",
              "SONARR4K_API_URL": "${{ vars.SONARR4K_API_URL }}",
              "RADARR_API_URL": "${{ vars.RADARR_API_URL }}",
              "RADARR4K_API_URL": "${{ vars.RADARR4K_API_URL }}"
            }
          },
          {
            "name": "straperr-selenium",
            "image": "selenium/standalone-chrome:latest",
            "network": "${{ vars.DOCKER_NETWORK_STRAPERR }}",
            "healthcheck_url": "http://localhost:4444/wd/hub/status",
            "memory_limit": "${{ vars.DOCKER_MEMORY_LIMIT_SELENIUM }}",
            "memory_reservation": "${{ vars.DOCKER_MEMORY_RESERVATION_SELENIUM }}",
            "env_vars": {
              "SE_ENABLE_TRACING": "false"
            }
          }
        ]

