# .github/workflows/remove-deploy.yml
name: Remove application from server

on:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' }}
    if: ${{ github.ref == 'refs/heads/main' }}

    outputs:
      environment: ${{ steps.get_variables.outputs.environment }}
      tag_version: ${{ steps.get_variables.outputs.tag_version }}
      repo_name: ${{ steps.get_variables.outputs.repo_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set environment output
        id: get_variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_BRANCH: ${{ github.ref }}
        run: |
          echo "environment=${{ github.ref == 'refs/heads/main' && 'production' }}" >> $GITHUB_OUTPUT
          echo "tag_version=$(git tag -l | sort -V | tail -n 1)" >> $GITHUB_OUTPUT
          echo "repo_name=$(echo ${{ env.GITHUB_REPOSITORY }} | awk -F/ '{print $2}')" >> $GITHUB_OUTPUT

      - name: Create setup summary
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_BRANCH: ${{ github.ref }}
          ENVIRONMENT: ${{ steps.get_variables.outputs.environment }}
          TAG_VERSION: ${{ steps.get_variables.outputs.tag_version }}
          REPO_NAME: ${{ steps.get_variables.outputs.repo_name }}
        run: |
          echo "## Setup Summary" >> $GITHUB_STEP_SUMMARY
          echo "### Output variables" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: ${{ env.ENVIRONMENT }}" >> $GITHUB_STEP_SUMMARY
          echo "- Tag version: [${{ env.TAG_VERSION }}](https://github.com/${{ env.GITHUB_REPOSITORY }}/releases/tag/${{ env.TAG_VERSION }})" >> $GITHUB_STEP_SUMMARY
          echo "- Repository name: [${{ env.REPO_NAME }}](https://github.com/${{ env.GITHUB_REPOSITORY }})" >> $GITHUB_STEP_SUMMARY

  remove-deploy:
    name: Remove application from server
    needs: [setup]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.setup.outputs.environment }}
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Add SSH private key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PROXY_PORT: ${{ secrets.SSH_PROXY_PORT }}
          SSH_PROXY_HOST: ${{ secrets.SSH_PROXY_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -p ${{ env.SSH_PROXY_PORT }} -H ${{ env.SSH_PROXY_HOST }} >> ~/.ssh/known_hosts

      - name: Add SSH config
        env:
          SSH_PRIVATE_HOST: ${{ secrets.SSH_PRIVATE_HOST }}
          SSH_PRIVATE_USER: ${{ secrets.SSH_PRIVATE_USER }}
          SSH_PRIVATE_PORT: ${{ secrets.SSH_PRIVATE_PORT }}
          SSH_PROXY_USER: ${{ secrets.SSH_PROXY_USER }}
          SSH_PROXY_HOST: ${{ secrets.SSH_PROXY_HOST }}
          SSH_PROXY_PORT: ${{ secrets.SSH_PROXY_PORT }}
        run: |
          echo "Host proxy
                HostName ${{ env.SSH_PRIVATE_HOST }}
                User ${{ env.SSH_PRIVATE_USER }}
                Port ${{ env.SSH_PRIVATE_PORT }}
                ProxyJump ${{ env.SSH_PROXY_USER }}@${{ env.SSH_PROXY_HOST }}:${{ env.SSH_PROXY_PORT }}
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null
          " >> ~/.ssh/config

      - name: Create docker context
        run: |
          docker context create proxy --docker host=ssh://proxy
          docker context use proxy

      - name: Remove application from server
        env:
          REPO_NAME: ${{ needs.setup.outputs.repo_name }}
        run: |
          if [ "$(docker ps -a -q -f name=${{ env.REPO_NAME }})" ]; then
            docker rm -f ${{ env.REPO_NAME }}
          fi

      - name: Remove old docker images
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          for DOCKER_IMAGE_ID in $(docker images -q ghcr.io/${{ env.GITHUB_REPOSITORY }}); do
            docker rmi -f $DOCKER_IMAGE_ID || true
          done

      - name: Create remove-deploy summary
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          TAG_VERSION: ${{ needs.setup.outputs.tag_version }}
          REPO_NAME: ${{ needs.setup.outputs.repo_name }}
        run: |
          echo "## Deploy Summary" >> $GITHUB_STEP_SUMMARY
          echo "- ${{ env.REPO_NAME }} container has been removed from server." >> $GITHUB_STEP_SUMMARY
